/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Yesica
 */
public class VtnInicio extends javax.swing.JFrame {

VtnObras vtnObras;
VtnAutores vtnAutores;
VtnExposiciones vtnExposiciones;

    /**
     * Creates new form Inicio
     */
    public VtnInicio() {
        initComponents();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExposiciones = new javax.swing.JButton();
        btnObras = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galería de arte");
        setName("VtnInicio"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("btnAutor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 810, -1, -1));

        jLabel2.setText("btnObras");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 800, -1, -1));

        jLabel3.setText("btnExposicion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 800, -1, -1));

        btnExposiciones.setBackground(java.awt.SystemColor.windowBorder);
        btnExposiciones.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btnExposiciones.setForeground(new java.awt.Color(255, 255, 255));
        btnExposiciones.setText("Exposiciones");
        btnExposiciones.setBorderPainted(false);
        btnExposiciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExposiciones.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnExposiciones.setOpaque(false);
        btnExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExposicionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnExposiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 770, 250, 100));

        btnObras.setBackground(java.awt.SystemColor.windowBorder);
        btnObras.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btnObras.setForeground(new java.awt.Color(255, 255, 255));
        btnObras.setText("Obras");
        btnObras.setBorderPainted(false);
        btnObras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnObras.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnObras.setOpaque(false);
        btnObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnObras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 770, 250, 100));

        btnAutores.setBackground(java.awt.SystemColor.windowBorder);
        btnAutores.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        btnAutores.setForeground(new java.awt.Color(255, 255, 255));
        btnAutores.setText("Autores");
        btnAutores.setBorderPainted(false);
        btnAutores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAutores.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAutores.setOpaque(false);
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 770, 250, 100));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo.png"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/galeria.jpeg"))); // NOI18N
        fondo.setName("lblfondo"); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 980));
        fondo.getAccessibleContext().setAccessibleName("lblfondo");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrasActionPerformed
        vtnObras = new VtnObras();
        vtnObras.setVisible(true);
        dispose();        
    }//GEN-LAST:event_btnObrasActionPerformed

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
         vtnAutores = new VtnAutores();
        vtnAutores.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExposicionesActionPerformed
       vtnExposiciones = new VtnExposiciones();
        vtnExposiciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExposicionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnExposiciones;
    private javax.swing.JButton btnObras;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
