/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import operaciones.OperacionesAutor;
import operaciones.OperacionesObras;
import pojos.Autor;

/**
 *
 * @author Yesica
 */
public class VtnObras extends javax.swing.JFrame {

    VtnInicio vtnInicio;
    DefaultComboBoxModel modeloAutores;
    DefaultComboBoxModel modeloTipoArte;
    OperacionesAutor operacionesAutor = new OperacionesAutor();
    OperacionesObras operacionesObras = new OperacionesObras();

    /**
     * Creates new form VtnObras
     */
    public VtnObras() {
        initComponents();
        cargarComboAutores();
        cargarComboTipoArte();
        jLabel4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        cmbAutor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        lblRegresar = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obras");
        setMinimumSize(new java.awt.Dimension(1030, 980));
        setPreferredSize(new java.awt.Dimension(1030, 980));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 370, 50));

        cmbAutor.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        cmbAutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 370, 50));

        jLabel4.setText("btnCrear");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Autor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo arte");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        btnCrear.setBackground(java.awt.SystemColor.windowBorder);
        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 210, 50));

        cmbTipo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 370, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 690, 450));

        lblRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonVolver.png"))); // NOI18N
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TituloObras.png"))); // NOI18N
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Obras.jpeg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, -1, 1030));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
        //vuelve a la pantalla de inicio y destruye esta
        vtnInicio = new VtnInicio();
        vtnInicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (comprobarDatos()) {
            String nombre = txtNombre.getText();
            Autor c = (Autor) cmbAutor.getSelectedItem();
            String tipo = cmbTipo.getSelectedItem().toString();
            //crea la obra en la bbdd
            boolean ok = operacionesObras.crearObra(nombre, tipo, c);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Obra creada exitosamente");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "Ha surgido un error");
            }
        }

    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cmbAutor;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    /**
     * Verifica si los datos ingresados son válidos.
     *
     * @return true si los datos son correctos, false de lo contrario.
     */
    private boolean comprobarDatos() {
        boolean correcto = false;
        String nombre = txtNombre.getText();
        //Comprobar si nombre tiene texto
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe introducir un nombre");
            txtNombre.requestFocus();
        } //comprobar si ha elegido autor
        else if (cmbAutor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe elegir un autor");
        } //comprobar si ha elegido un tipo
        else if (cmbTipo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Elija una categoría");
        } else {
            correcto = true;
        }
        return correcto;
    }

    /**
     * Limpia los campos de entrada de texto y restablece los ComboBox a sus
     * valores predeterminados.
     */
    private void limpiar() {
        txtNombre.setText("");
        cmbAutor.setSelectedIndex(0);
        cmbTipo.setSelectedIndex(0);
    }

    /**
     * Carga los autores disponibles en el ComboBox de autores.
     */
    private void cargarComboAutores() {
        modeloAutores = new DefaultComboBoxModel();
        cmbAutor.setModel(modeloAutores);
        modeloAutores.addElement("--Seleccione un autor--");
        //Ejecutar busqueda
        List<Autor> autores = operacionesAutor.obtenerTodosLosAutores();
        //añadirlos al combo
        for (Autor autor : autores) {
            modeloAutores.addElement(autor);
        }
    }

    /**
     * Carga los tipos de arte disponibles en el ComboBox de tipos de arte.
     */
    private void cargarComboTipoArte() {
        modeloTipoArte = new DefaultComboBoxModel();
        cmbTipo.setModel(modeloTipoArte);
        modeloTipoArte.addElement("--Seleccione un tipo--");
        modeloTipoArte.addElement("Pintura");
        modeloTipoArte.addElement("Escultura");
        modeloTipoArte.addElement("Fotografía");
        modeloTipoArte.addElement("Grabado");
    }

}
