package pojos;
// Generated 29-ene-2024 10:07:31 by Hibernate Tools 4.3.1



/**
 * ExposicionId generated by hbm2java
 */
public class ExposicionId  implements java.io.Serializable {


     private int idExposicion;
     private int idObra;

    public ExposicionId() {
    }

    public ExposicionId(int idExposicion, int idObra) {
       this.idExposicion = idExposicion;
       this.idObra = idObra;
    }
   
    public int getIdExposicion() {
        return this.idExposicion;
    }
    
    public void setIdExposicion(int idExposicion) {
        this.idExposicion = idExposicion;
    }
    public int getIdObra() {
        return this.idObra;
    }
    
    public void setIdObra(int idObra) {
        this.idObra = idObra;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExposicionId) ) return false;
		 ExposicionId castOther = ( ExposicionId ) other; 
         
		 return (this.getIdExposicion()==castOther.getIdExposicion())
 && (this.getIdObra()==castOther.getIdObra());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdExposicion();
         result = 37 * result + this.getIdObra();
         return result;
   }   


}


