package pojos;
// Generated 29-ene-2024 10:07:31 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Exposicion generated by hbm2java
 */
public class Exposicion  implements java.io.Serializable {


     private ExposicionId id;
    private List<Obra> obras = new ArrayList<>();
     private Sala sala;
     private String nombre;
     private Date fechAlta;
     private Date fechBaja;
     private Obra obra;
   
   

    public Exposicion() {
    }
    
 

    public Exposicion(ExposicionId id, Sala sala, String nombre, Date fechAlta, Date fechBaja) {
        this.id = id;
        this.sala = sala;
        this.nombre = nombre;
        this.fechAlta = fechAlta;
        this.fechBaja = fechBaja;
    }

    // Getters y Setters para id, sala, nombre, fechAlta y fechBaja

    public Obra getObra(){
        return obra;
    }
    
    public void setObra(Obra obra){
        this.obra=obra;
    }
    public List<Obra> getObras() {
        return this.obras;
    }

    public void setObras(List<Obra> obras) {
        this.obras = obras;
    }

    public void addObra(Obra obra) {
        this.obras.add(obra);
    }
   
    public ExposicionId getId() {
        return this.id;
    }
    
    public void setId(ExposicionId id) {
        this.id = id;
    }
   
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechAlta() {
        return this.fechAlta;
    }
    
    public void setFechAlta(Date fechAlta) {
        this.fechAlta = fechAlta;
    }
    public Date getFechBaja() {
        return this.fechBaja;
    }
    
    public void setFechBaja(Date fechBaja) {
        this.fechBaja = fechBaja;
    }

    @Override
    public String toString() {
        return nombre;
    }



}


