package pojos;
// Generated 29-ene-2024 10:07:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private int idSala;
     private String nombre;
     private Set exposicions = new HashSet(0);

    public Sala() {
    }

	
    public Sala(int idSala, String nombre) {
        this.idSala = idSala;
        this.nombre = nombre;
    }
    public Sala(int idSala, String nombre, Set exposicions) {
       this.idSala = idSala;
       this.nombre = nombre;
       this.exposicions = exposicions;
    }
   
    public int getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(int idSala) {
        this.idSala = idSala;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getExposicions() {
        return this.exposicions;
    }
    
    public void setExposicions(Set exposicions) {
        this.exposicions = exposicions;
    }

    @Override
    public String toString() {
        return nombre;
    }




}


